server:
  port: 64001

app:
  ConnectTimeout: 100
  ReadTimeout: 5000
 
#子配置文件
spring.profiles.include: url
 
druid:
    dbType: dm
    url: jdbc:dm://${csse.dmdba.url}/TYYY_TXL_APP_DB
    username: TYYY_TXL_APP_DB
    password: Lc5/rBYlaDGn2MF/g5xorNVZ6PDEwxdwFkOpkVh5TRlFGp3+0gHQm4RBw3lR+OQIT4EqpwNS/U1zF7G4C3cIgg==
    initial-size: 1
    min-idle: 1
    max-active: 10 
    maxWait: 3000
    test-on-borrow: true
    testWhileIdle: true
    validationQuery: select 1 from DUAL 
    filters: config
    connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIjkuPg8jCTRqX8rHkXoVsRsBEBbVlaAwEPYmMBG8D7EqMR7bF6OGS3rNnH8I6p4b7x4YhYVj/3+31ZABR87gDsCAwEAAQ==

mybatis.configuration.mapUnderscoreToCamelCase: true

logging:
  file: ${csse.log.path}
  level:
#    root: info
    com: 
      css: debug

spring:
  application:
    name: SinglePlatform

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#单点登录配置（新）
csse:
  mircoservice:
    oauth2:
      client:
        accessTokenUri: ${csse.mircoservice.zuul}/api/uaa/oauth/token
        clientId: ${csse.txl.appId}
        clientSecret: ${csse.txl.appSecret}
  sso: 
    server: 
      url: ${csse.mircoservice.zuul}
      no-auth-suffixs: js,css,font,png,jpg,jpeg,htm,ico,pdf,ofd,wps,doc
      api: 
        checkToken: api/sso/valtoken/  
        userinfo: api/sso/user/

#消息格式
msg:
  type: application
  appid: 
  display: 
    system: 
    notification: 
    msgbox: 
  action: 
    anstore: 
    deployment: 

#判断当前登录者是否为应用的管理员
csse.mircoservice.app: /api/app/application/manager
#组织机构增量同步接口
csse.mircoservice.syncdepartments: /api/org/syncdepartments

#数据库配置地址
csse.dmdba.url: dm
#应用的appID
csse.txl.appId: cpk.csse.txl
#应用的secret
csse.txl.appSecret: AC10074F-9DB6-4e2f-9BD6-F06AD6167853
#日志输出路径
csse.log.path: c:/temp/storetemp/txl_app.log